### ISSUE TITLE
PopupSource break ListComboBox

### ISSUE THREAD

**Issue by BlackGlory** [elix/elix#162] opened 2021-01-15 10:38 UTC
This bug cannot be reproduced on codepen, please create an html file manually and open it in a browser.

```html
<script type="module" src="https://cdn.jsdelivr.net/gh/elix/elix@main/define/ListComboBox.js"></script>

<elix-list-combo-box>
  <div>1</div>
  <div>2</div>
  <div>3</div>
</elix-list-combo-box>
```

![Snipaste_2021-01-15_18-37-17](https://user-images.githubusercontent.com/1365962/104714911-bf20b200-5760-11eb-96ff-4a75ea12897e.png)

The component will be displayed incorrectly, and the list cannot be opened. If you turn off PopupSource's height style, it returns to normal.

```css
[part~="source"] {
    height: 100%; /* this line */
    -webkit-tap-highlight-color: transparent;
    touch-action: manipulation;
    width: 100%;
}
```

**Comment by JanMiksovsky** [comment] 2021-01-15 19:05
I cannot reproduce the problem you describe: I end up with a ListComboBox which is mostly functional, although its presentation isn't quite complete.

The incomplete presentation is a bug. I hadn't noticed the issue before now because ListComboBox is mostly intended as a base class; the components designed for immediate reuse are the subclasses AutoCompleteComboBox and FilterListComboBox. If you need a basic combo box, then AutoCompleteComboBox is a better choice than ListComboBox.

Still, ListComboBox should be usable on its own. I've checked in a fix for the presentation issue, so ListComboBox should now look like AutoCompleteComboBox. It should also basically work the same, with the notable difference that ListComboBox doesn't include auto-complete behavior in the input.

While my fix should make the component look a little better, that fix shouldn't have any impact on the popup height. If that's correct, then I expect you'll still see the problem you describe.

In which case I could use a bit more detail in order to reproduce the problem. Please let me know what OS and browser version you're using. Additionally, if it'd be possible for you to share a clean repro case in a complete web page, that might help ensure that I can see what you're seeing.

**Comment by BlackGlory** [comment] 2021-01-16 01:51
The same code (saved as proof.html), this is the current result.

OS: Windows 10 20H2 (OS Build 19042.746)

Edge 87.0.664.75
![edge 87 0 664 75](https://user-images.githubusercontent.com/1365962/104794011-0437f900-57e0-11eb-80c8-6e0705acbb67.png)

Firefox 84.0.2
![firefox 84 0 2](https://user-images.githubusercontent.com/1365962/104794015-069a5300-57e0-11eb-97fd-1861e9f15684.png)

Chrome 87.0.4280.141
![chrome 87 0 4280 141](https://user-images.githubusercontent.com/1365962/104794051-39444b80-57e0-11eb-8e48-6127a7b6725f.png)

**Comment by BlackGlory** [comment] 2021-01-16 01:55
Then disable "height: 100%".

Edge:
![edge-after](https://user-images.githubusercontent.com/1365962/104794163-d901d980-57e0-11eb-9975-dcf581622a3e.png)

Firefox:
![firefox-after](https://user-images.githubusercontent.com/1365962/104794170-dd2df700-57e0-11eb-8224-1ee299c2daa2.png)

Chrome:
![chrome-after](https://user-images.githubusercontent.com/1365962/104794174-e323d800-57e0-11eb-8981-1f21301fecb3.png)

**Comment by JanMiksovsky** [comment] 2021-01-20 01:12
I'm still not seeing what you're seeing.

So that we can be sure we're using the same source, I've posted your snippet with minimal HTML boilerplate to https://gist.github.com/JanMiksovsky/ef031404f9edfe0144e3878f86b9a97c.

When I open that on Windows in Edge, Firefox, or Chrome, they all show the combo box working as expected:

<img width="960" alt="proof" src="https://user-images.githubusercontent.com/86139/105113099-24ceb000-5a79-11eb-9fca-531ca7799dbb.png">

My Windows version is 10.0.18363, which is somewhat older than yours. (I'm currently updating the device to see if that makes a difference.)

Can you verify that no external styling is being applied to the combo box? From your images, my only guess is that there's some styling on the page that makes the combo box taller than its default height.

The reason we can't just take out the `height: 100%` is that that styling is there to allow someone to deliberately make the combo box a different height (e.g., taller) than the default. So I want to understand this problem rather than working around it.

**Comment by BlackGlory** [comment] 2021-01-20 02:36
I found that the key difference is whether `<!DOCTYPE html>` exists. In Quirks Mode, this behavior occurs. I am not sure if this can be fixed.

**Closed** 2021-01-20 02:38 UTC

**Comment by JanMiksovsky** [comment] 2021-01-20 03:05
Wow, that's bizarre. I'd forgotten about quirks mode.

Glad to have a diagnosis. Thanks for your participation in driving this to closure.
