### ISSUE TITLE
FilterComboBox - when tap on item in list it sometimes does not get selected

### ISSUE THREAD

**Issue by jmagaram** [elix/elix#153] opened 2020-12-21 20:49 UTC
I'm using this in Blazor and it seems to work most of the time. But occasionally I tap on an item in the list and the pick-list closes but does NOT select the item I clicked on. Try this...

https://codepen.io/jmagaram/full/LYRjXEZ

(1) Clear the text field
(2) Type "1"
(3) You'll see a couple matches - "1 bag" and "13 bunches" - with neither selected.
(3) Tap with your finger on "13 bunches". The list closes and the selected item is "1".

I've tried this on Windows 10 with touch screen and on my iPhone. Sometimes I need to repeat this sequence a bunch of times before it fails. It seems to work and then sometimes it doesn't and I wonder - did I click/tap on the list item? I've zoomed the web page to 200% so the click targets are bigger.

**Comment by JanMiksovsky** [comment] 2021-01-03 23:29
I had a bit of time today to reproduce this flaky behavior; thanks for reporting it. Worse, it looks like auto-complete in FilterComboBox is broken on the master branch generally.

Will dig into this as soon as I can.

**Comment by JanMiksovsky** [comment] 2021-01-07 00:54
Trying to pin this down. There's at least one issue going on, perhaps more.

A reliable repro of one of the issues that can be found in the stock [FilterComboBox demo](https://component.kitchen/demos/filterComboBox.html):
* Type the beginning of any item. E.g., type "a".
* Select an item, e.g., "Acai". The list closes.
* Type the same character ("a"). The list reopens.
* Select the same item as before ("Acai").
Expected result: the combo box is left with "Acai" in the text box.
Actual result: the combo box is left with "a" in the text box.

It looks like a certain degree of logic is triggered only when the selected item _changes_. If the item doesn't change, then the combo box doesn't properly update.

I'll continue to investigate.

**Comment by JanMiksovsky** [comment] 2021-01-07 01:46
I've pushed a fix for the above issue; it's now on the new `main` branch (which supercedes the previous `master` branch).

[Demo](https://codepen.io/JanMiksovsky/pen/QWKxgrN)

As far as I can tell, the component now seems to work as expected. Please verify when you have a chance.

**Comment by JanMiksovsky** [comment] 2021-01-09 01:40
Hmm... it looks like the CDN wasn't serving the right file in the above demo. I've updated the demo to use jsdelivr.net; the demo seems to work again now.

**Comment by JanMiksovsky** [comment] 2021-01-21 21:20
I think this is now solved, please reopen if you still see problems.

**Closed by JanMiksovsky** 2021-01-21 21:20 UTC
